base_url: http://goingunderground.herokuapp.com/stations/arriving/
interval: 0.1
pause: 1
lights:
  - 15
  - 18
  - 23
  - 24
  - 25
  - 8
  - 7
  - 12

button: 21
station: euston
direction: southbound

valid_stations:

stations:
  - walthamstow_central
  - blackhorse_road
  - tottenham_hale
  - seven_sisters
  - finsbury_park
  - highbury_and_islington
  - kings_cross_st_pancras
  - euston
  - warren_street
  - oxford_circus
  - green_park
  - victoria
  - pimlico
  - vauxhall
  - stockwell
  - brixton
